dist: xenial
language: java
sudo: true
jdk: openjdk14
install:
  - mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
  - chmod +x mvnw
cache:
  directories:
    - $HOME/.m2